### ISSUE TITLE
Add to CTAN

### ISSUE THREAD

**Issue by emichael** [alecjacobson/coloremoji.sty#5]
There are certainly issues with the package, but it seems to work pretty well! Why not add it to the CTAN (with some <1 version number)?

https://www.ctan.org/upload?lang=en

**Comment by sieversMartin** [comment]
I can help you with uploading if you want.

**Comment by wilx** [comment]
I would like to see this on CTAN, too. I could totally use this in my [tweet2latex](https://github.com/wilx/tweet2latex) tool.

**Comment by Aariq** [comment]
I would also love to have it on CTAN as I'm having trouble installing it from the command line.

**Comment by alecjacobson** [comment]
what is the process for adding it? Does somebody want to do it?

**Comment by eivindml** [comment]
It's just a matter of uploading a `.zip` file. Instructions can be found here: https://ctan.org/help/upload-pkg 

Should take 5-10 minutes.

**Comment by alecjacobson** [comment]
OK, submitted. Let's see.

**Comment by wilx** [comment]
It is there now. This issue can be closed.
